// 카테고리별 상품 객체 분리
const vgaProducts = {
  "a": {
  name: "갤럭시 GALAX 지포스 RTX 4070 Ti SUPER EX GAMER WHITE OC D6X 16GB",
  category: "vga",
  price: "₩1,915,800",  
  popularity: 20,  
  new: 8,
  chipset: "RTX 4070 Ti SUPER",
  image: "./img/product00.png",
  desc: [
      "갤럭시 GALAX 지포스 RTX 4070 Ti SUPER EX GAMER WHITE OC D6X 16GB",
      "NVIDIA RTX 4070 Ti SUPER",
      "4nm",
      "2340MHz",
      "2640MHz",
      "2655MHz",
      "8448개",
      "PCIe 4.0 x16",
      "GDDR6X",
      "16GB",
      "HDMI2.1 x1, DP1.4 x3",
      "8K 지원, HDR 지원, HDCP 2.3, 제로팬(0-dB 기술)",
      "285W",
      "정격파워 750W 이상",
      "16핀 (12VHPWR) x1",
      "323mm",
      "60mm",
      "3팬, 제로팬 기술, LED 라이트 탑재, 백플레이트 포함, XTREME TUNER 지원",
      "3년 무상 보증"
  ]
},
  "b": {
      name: "이엠텍 지포스 RTX 5070 MIRACLE WHITE D7 12GB",
      category: "vga",
      price: "₩1,044,000",
  popularity: 2,
      new: 13,
      chipset: "RTX 5070",
      image: "./img/product01.png",
      desc: [
          "이엠텍 지포스 RTX 5070 MIRACLE WHITE D7 12GB",
          "NVIDIA RTX 5070",
          "4nm",
          "2325MHz",
          "2512MHz",
          "6144개",
          "PCIe 5.0 x16",
          "GDDR7",
          "12GB",
          "192bit",
          "HDMI2.1 x1, DP2.1 x3",
          "8K 지원, HDR 지원, HDCP 2.3, 제로팬(0-dB 기술)",
          "정격파워 650W 이상",
          "16핀 (12V2x6) x1",
          "329mm",
          "45mm",
          "3팬, 제로팬 기술, LED 라이트 탑재, 백플레이트 포함, DrMOS 기술 적용",
          "3년보증"
      ]
  },
  "c": {
      name: "MSI 지포스 RTX 5080 뱅가드 SOC D7 16GB 하이퍼프로져",
      category: "vga",
      price: "₩2,293,200",
  popularity: 7,
      new: 3,
      chipset: "RTX 5080",
      image: "./img/product02.png",
      desc: [
          "MSI 지포스 RTX 5080 뱅가드 SOC D7 16GB 하이퍼프로져",
          "NVIDIA RTX 5080",
          "TSMC 4nm",
          "2730MHz",
          "2745MHz",
          "10752개",
          "PCIe 5.0 x16",
          "GDDR7",
          "16GB",
          "HDMI2.1 x1, DP2.1 x3",
          "8K 지원, HDR 지원, HDCP 2.3, 제로팬(0-dB 기술)",
          "360W",
          "정격파워 850W 이상",
          "16핀 (12V2x6) x1",
          "357mm",
          "66mm",
          "3팬, 제로팬 기술, LED 라이트 탑재, 백플레이트 포함, DrMOS 기술 적용, Dual BIOS 지원, MYSTIC LIGHT 기능 포함",
          "3년 무상 보증"
      ]
  },
  "d": {
      name: "갤럭시 GALAX 지포스 RTX 5070 EX GAMER WHITE OC D7 12GB",
      category: "vga",
      price: "₩1,099,900",
  popularity: 3,
      new: 14,
      chipset: "RTX 5070",
      image: "./img/product03.png",
      desc: [
          "갤럭시 GALAX 지포스 RTX 5070 EX GAMER WHITE OC D7 12GB",
          "NVIDIA RTX 5070",
          "4nm",
          "2325MHz",
          "2557MHz",
          "6144개",
          "PCIe 5.0 x16",
          "GDDR7",
          "12GB",
          "HDMI2.1 x1, DP2.1 x3",
          "8K 지원, HDR 지원, HDCP 2.3, 제로팬(0-dB 기술)",
          "250W",
          "정격파워 650W 이상",
          "16핀 (12V2x6) x1",
          "322mm",
          "52mm",
          "3팬, 제로팬 기술, LED 라이트 탑재, 백플레이트 포함",
          "3년 무상 보증"
      ]
  },
  "e": {
      name: "MSI 지포스 RTX 5070 게이밍 트리오 OC D7 12GB 트라이프로져4",
      category: "vga",
      price: "₩1,148,960",
  popularity: 4,
      new: 15,
      chipset: "RTX 5070",
      image: "./img/product04.png",
      desc: [
          "MSI 지포스 RTX 5070 게이밍 트리오 OC D7 12GB 트라이프로져4",
          "NVIDIA RTX 5070",
          "4nm",
          "2325MHz",
          "2610MHz",
          "2625MHz",
          "6144개",
          "PCIe 5.0 x16",
          "GDDR7",
          "12GB",
          "HDMI2.1 x1, DP2.1 x3",
          "8K 지원, HDR 지원, HDCP 2.3, 제로팬(0-dB 기술)",
          "250W",
          "정격파워 650W 이상",
          "16핀 (12V2x6) x1",
          "338mm",
          "50mm",
          "3팬, 제로팬 기술, 백플레이트 포함, DrMOS 기술 적용, LED 라이트 탑재, MYSTIC LIGHT 기능 포함",
          "3년 무상 보증"
      ]
  },
  "vga1": {
  name: "갤럭시 GALAX 지포스 RTX 5070 Ti EX GAMER WHITE OC D7 16GB",
  category: "vga",
  price: "₩1,470,780",
  popularity: 1,
  new: 10,
      chipset: "RTX 5070 Ti",
  image: "./img/vga1.png",
  desc: [
      "갤럭시 GALAX 지포스 RTX 5070 Ti EX GAMER WHITE OC D7 16GB",
      "NVIDIA RTX 5070 Ti",
      "PCIe5.0x16",
      "정격파워750W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 322mm",
      "베이스클럭: 2295MHz",
      "부스트클럭: 2497MHz",
      "스트림 프로세서: 8960개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 300W",
      "3팬",
      "두께: 52mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "XTREME TUNER",
      "구성품: VGA지지대, 3x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga2": {
  name: "PALIT 지포스 RTX 5060 Ti Infinity 3 D7 16GB 이엠텍",
  category: "vga",
  price: "₩751,290",
  popularity: 5,
  new: 18,
      chipset: "RTX 5060 Ti",
  image: "./img/vga2.png",
  desc: [
      "PALIT 지포스 RTX 5060 Ti Infinity 3 D7 16GB 이엠텍",
      "NVIDIA RTX 5060 Ti",
      "PCIe5.0x16(at x8)",
      "정격파워600W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 291.9mm",
      "베이스클럭: 2407MHz",
      "부스트클럭: 2572MHz",
      "스트림 프로세서: 4608개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 180W",
      "3팬",
      "두께: 41.3mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS",
      "ThunderMaster",
      "A/S 3년"
  ]
},
"vga3": {
  name: "갤럭시 GALAX 지포스 RTX 5080 WHITE OC D7 16GB",
  category: "vga",
  price: "₩1,858,000",
  popularity: 6,
  new: 4,
      chipset: "RTX 5080",
  image: "./img/vga3.png",
  desc: [
      "갤럭시 GALAX 지포스 RTX 5080 WHITE OC D7 16GB",
      "NVIDIA RTX 5080",
      "PCIe5.0x16",
      "정격파워850W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 303mm",
      "베이스클럭: 2295MHz",
      "부스트클럭: 2625MHz",
      "스트림 프로세서: 10752개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDCP 2.3",
      "사용전력: 360W",
      "3팬",
      "두께: 49.7mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "구성품: VGA지지대, 3x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga4": {
  name: "MSI 지포스 RTX 4060 벤투스 2X 블랙 OC D6 8GB",
  category: "vga",
  price: "₩527,990",
  popularity: 8,
  new: 31,
      chipset: "RTX 406",
  image: "./img/vga4.png",
  desc: [
      "MSI 지포스 RTX 4060 벤투스 2X 블랙 OC D6 8GB",
      "NVIDIA RTX 4060",
      "PCIe4.0x16(at x8)",
      "정격파워550W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 199mm",
      "부스트클럭: 2490MHz",
      "OC클럭: 2505MHz",
      "스트림 프로세서: 3072개",
      "GDDR6",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 115W",
      "2팬",
      "두께: 41mm",
      "제로팬(0-dB기술)",
      "백플레이트"
  ]
},
"vga5": {
  name: "ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB",
  category: "vga",
  price: "₩916,460",
  popularity: 9,
  new: 16,
      chipset: "RTX 5070",
  image: "./img/vga5.png",
  desc: [
      "ZOTAC GAMING 지포스 RTX 5070 SOLID OC D7 12GB",
      "NVIDIA RTX 5070",
      "PCIe5.0x16",
      "정격파워650W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 304.4mm",
      "베이스클럭: 2325MHz",
      "부스트클럭: 2542MHz",
      "스트림 프로세서: 6144개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 250W",
      "전원부: 9+3페이즈",
      "3팬",
      "두께: 41.6mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "구성품: VGA지지대, 2x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga6": {
  "name": "이엠텍 지포스 RTX 5080 MIRACLE WHITE D7 16GB",
  "category": "vga",
  "price": "₩1,987,920",
  "popularity": 10,
  "new": 5,
  "chipset": "RTX 5080",
  "image": "./img/vga6.png",
  "desc": [
      "이엠텍 지포스 RTX 5080 MIRACLE WHITE D7 16GB",
      "PCIe5.0x16 인터페이스",
      "정격파워 850W 이상 요구",
      "16핀(12V2x6) 전원 포트",
      "가로 길이: 348mm",
      "베이스클럭: 2295MHz",
      "부스트클럭: 2617MHz",
      "스트림 프로세서: 10752개",
      "GDDR7 메모리 적용",
      "출력단자: HDMI2.1, DP2.1",
      "최대 360W 전력 소모",
      "3팬 쿨링 시스템",
      "62mm 두께 방열판",
      "제로팬(0-dB) 기술 적용",
      "강화 백플레이트 장착",
      "DrMOS 전원부 구성",
      "화이트 LED 라이트링",
      "구성품: VGA지지대, 3x8핀 to 16핀 커넥터",
      "3년 A/S 보증"
  ]
},
"vga7": {
  name: "MSI 지포스 RTX 5070 게이밍 트리오 OC D7 12GB 트라이프로져4",
  category: "vga",
  price: "₩1,044,980",
  popularity: 11,
  new: 17,
      chipset: "RTX 5070",
  image: "./img/vga7.png",
  desc: [
      "MSI 지포스 RTX 5070 게이밍 트리오 OC D7 12GB 트라이프로져4",
      "NVIDIA RTX 5070",
      "PCIe5.0x16",
      "정격파워650W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 338mm",
      "베이스클럭: 2325MHz",
      "부스트클럭: 2610MHz",
      "OC클럭: 2625MHz",
      "스트림 프로세서: 6144개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 250W",
      "3팬",
      "두께: 50mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS",
      "LED 라이트",
      "MYSTIC LIGHT",
      "구성품: VGA지지대, 2x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga8": {
  name: "PALIT 지포스 RTX 5070 Ti GAMINGPRO D7 16GB 이엠텍",
  category: "vga",
  price: "₩1,358,000",
  popularity: 12,
  new: 11,
      chipset: "RTX 5070 Ti",
  image: "./img/vga8.png",
  desc: [
      "PALIT 지포스 RTX 5070 Ti GAMINGPRO D7 16GB 이엠텍",
      "NVIDIA RTX 5070 Ti",
      "PCIe5.0x16",
      "정격파워750W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 331.9mm",
      "베이스클럭: 2295MHz",
      "부스트클럭: 2452MHz",
      "스트림 프로세서: 8960개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 300W",
      "3팬",
      "두께: 60mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "Dual BIOS",
      "PWM 커넥터",
      "ThunderMaster",
      "구성품: 2x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga9": {
  name: "갤럭시 GALAX 지포스 RTX 5060 Ti BLACK OC D7 8GB",
  category: "vga",
  price: "₩630,560",
  popularity: 13,
  new: 19,
      chipset: "RTX 5060 Ti",
  image: "./img/vga9.png",
  desc: [
      "갤럭시 GALAX 지포스 RTX 5060 Ti BLACK OC D7 8GB",
      "NVIDIA RTX 5060 Ti",
      "PCIe5.0x16(at x8)",
      "정격파워600W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 235mm",
      "베이스클럭: 2407MHz",
      "부스트클럭: 2587MHz",
      "스트림 프로세서: 4608개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 180W",
      "2팬",
      "두께: 40mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "LED온오프스위치",
      "A/S 3년"
  ]
},
"vga10": {
  name: "ASUS ROG Astral 지포스 RTX 5090 OC D7 32GB 대원씨티에스",
  category: "vga",
  price: "₩5,744,370",
  popularity: 14,
  new: 1,
      chipset: "지포스 RTX 5090",
  image: "./img/vga10.png",
  desc: [
      "ASUS ROG Astral 지포스 RTX 5090 OC D7 32GB 대원씨티에스",
      "NVIDIA RTX 5090",
      "PCIe5.0x16",
      "정격파워850W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 357.6mm",
      "부스트클럭: 2580MHz",
      "OC클럭: 2610MHz",
      "스트림 프로세서: 21760개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "4팬",
      "두께: 76mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "AURA SYNC",
      "구성품: VGA지지대, 4x8핀 to 16핀 커넥터"
  ]
},
"vga11": {
  name: "ZOTAC GAMING 지포스 RTX 5060 Ti Twin Edge OC D7 16GB",
  category: "vga",
  price: "₩738,980",
  popularity: 15,
  new: 20,
      chipset: "RTX 5060 Ti",
  image: "./img/vga11.png",
  desc: [
      "ZOTAC GAMING 지포스 RTX 5060 Ti Twin Edge OC D7 16GB",
      "NVIDIA RTX 5060 Ti",
      "PCIe5.0x16(at x8)",
      "정격파워650W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 220.5mm",
      "베이스클럭: 2407MHz",
      "부스트클럭: 2602MHz",
      "스트림 프로세서: 4608개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 180W",
      "전원부: 5+2페이즈",
      "2팬",
      "두께: 41mm",
      "제로팬(0-dB기술)",
      "백플레이트"
  ]
},
"vga12": {
  name: "GIGABYTE 지포스 RTX 4060 Ti WINDFORCE OC D6 8GB 제이씨현",
  category: "vga",
  price: "₩599,450",
  popularity: 16,
  new: 27,
      chipset: "RTX 4060 Ti",
  image: "./img/vga12.png",
  desc: [
      "GIGABYTE 지포스 RTX 4060 Ti WINDFORCE OC D6 8GB 제이씨현",
      "NVIDIA RTX 4060 Ti",
      "PCIe4.0x16(at x8)",
      "정격파워500W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 201mm",
      "부스트클럭: 2550MHz",
      "스트림 프로세서: 4352개",
      "GDDR6",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원",
      "2팬",
      "두께: 41mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "A/S 3년"
  ]
},
"vga13": {
  name: "MSI 지포스 RTX 5090 슈프림 SOC D7 32GB 하이퍼프로져",
  category: "vga",
  price: "₩5,335,000",
  popularity: 17,
  new: 2,
      chipset: "RTX 5090",
  image: "./img/vga13.png",
  desc: [
      "MSI 지포스 RTX 5090 슈프림 SOC D7 32GB 하이퍼프로져",
      "NVIDIA RTX 5090",
      "PCIe5.0x16",
      "정격파워1000W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 359mm",
      "부스트클럭: 2565MHz",
      "OC클럭: 2580MHz",
      "스트림 프로세서: 21760개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 600W",
      "3팬",
      "두께: 76mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS",
      "LED 라이트",
      "Dual BIOS",
      "MYSTIC LIGHT",
      "구성품: VGA지지대, 4x8핀 to 16핀 커넥터"
  ]
},
"vga14": {
  name: "MSI 지포스 RTX 4060 Ti 벤투스 2X 블랙 OC D6 8GB",
  category: "vga",
  price: "₩609,390",
  popularity: 18,
  new: 28,
      chipset: "RTX 4060 Ti",
  image: "./img/vga14.png",
  desc: [
      "MSI 지포스 RTX 4060 Ti 벤투스 2X 블랙 OC D6 8GB",
      "NVIDIA RTX 4060 Ti",
      "PCIe4.0x16(at x8)",
      "정격파워550W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 199mm",
      "부스트클럭: 2565MHz",
      "OC클럭: 2580MHz",
      "스트림 프로세서: 4352개",
      "GDDR6",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 160W",
      "2팬",
      "두께: 42mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS"
  ]
},
"vga15": {
  name: "갤럭시 GALAX 지포스 RTX 4060 WHITE OC D6 8GB",
  category: "vga",
  price: "₩500,000",
  popularity: 19,
  new: 32,
      chipset: "RTX 4060",
  image: "./img/vga15.png",
  desc: [
      "갤럭시 GALAX 지포스 RTX 4060 WHITE OC D6 8GB",
      "NVIDIA RTX 4060",
      "PCIe4.0x16(at x8)",
      "정격파워550W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 237mm",
      "베이스클럭: 1830MHz",
      "부스트클럭: 2475MHz",
      "스트림 프로세서: 3072개",
      "GDDR6",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 115W",
      "2팬",
      "두께: 41mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "XTREME TUNER",
      "A/S 3년"
  ]
},
"vga16": {
  name: "MSI 지포스 RTX 4060 Ti 벤투스 2X 블랙 OC D6 16GB",
  category: "vga",
  price: "₩711,000",
  popularity: 21,
  new: 29,
      chipset: "RTX 4060 Ti",
  image: "./img/vga16.png",
  desc: [
      "MSI 지포스 RTX 4060 Ti 벤투스 2X 블랙 OC D6 16GB",
      "NVIDIA RTX 4060 Ti",
      "PCIe4.0x16(at x8)",
      "정격파워550W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 199mm",
      "부스트클럭: 2610MHz",
      "OC클럭: 2625MHz",
      "스트림 프로세서: 4352개",
      "GDDR6",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 165W",
      "2팬",
      "두께: 42mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS"
  ]
},
"vga17": {
  name: "MSI 지포스 RTX 5090 뱅가드 SOC D7 32GB 하이퍼프로져",
  category: "vga",
  price: "₩4,894,640",
  popularity: 22,
  new: 6,
      chipset: "RTX 5090",
  image: "./img/vga17.png",
  desc: [
      "MSI 지포스 RTX 5090 뱅가드 SOC D7 32GB 하이퍼프로져",
      "NVIDIA RTX 5090",
      "PCIe5.0x16",
      "정격파워1000W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 357mm",
      "부스트클럭: 2512MHz",
      "OC클럭: 2527MHz",
      "스트림 프로세서: 21760개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 575W",
      "3팬",
      "두께: 76mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS",
      "LED 라이트",
      "Dual BIOS",
      "구성품: VGA지지대, 4x8핀 to 16핀 커넥터"
  ]
},
"vga18": {
  name: "GIGABYTE 지포스 RTX 4080 SUPER AERO OC D6X 16GB",
  category: "vga",
  price: "₩2,955,990",
  popularity: 23,
  new: 9,
      chipset: "RTX 4080 SUPER",
  image: "./img/vga18.png",
  desc: [
      "GIGABYTE 지포스 RTX 4080 SUPER AERO OC D6X 16GB",
      "NVIDIA RTX 4080 SUPER",
      "PCIe4.0x16",
      "정격파워850W 이상",
      "전원 포트: 16핀(12VHPWR) x1",
      "가로(길이): 342mm",
      "베이스클럭: 2295MHz",
      "부스트클럭: 2595MHz",
      "스트림 프로세서: 10240개",
      "GDDR6X",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "3팬",
      "두께: 75mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "Dual BIOS",
      "RGB FUSION",
      "구성품: Anti-Sag브라켓, 3x8핀 to 16핀 커넥터",
      "A/S 4년"
  ]
},
"vga19": {
  name: "MSI 지포스 RTX 4090 게이밍 X 슬림 D6X 24GB 트라이프로져3",
  category: "vga",
  price: "₩5,299,000",
  popularity: 24,
  new: 33,
      chipset: "RTX 4090",
  image: "./img/vga19.png",
  desc: [
      "MSI 지포스 RTX 4090 게이밍 X 슬림 D6X 24GB 트라이프로져3",
      "NVIDIA RTX 4090",
      "PCIe4.0x16",
      "정격파워850W 이상",
      "전원 포트: 16핀(12VHPWR) x1",
      "가로(길이): 322mm",
      "부스트클럭: 2595MHz",
      "OC클럭: 2610MHz",
      "스트림 프로세서: 16384개",
      "GDDR6X",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 최대 450W",
      "3팬",
      "두께: 62mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS",
      "LED 라이트",
      "Dual BIOS",
      "MYSTIC LIGHT",
      "구성품: VGA지지대, 2x8핀 to 16핀 커넥터"
  ]
},
"vga20": {
  name: "GIGABYTE 지포스 RTX 4070 SUPER WINDFORCE OC D6X 12GB",
  category: "vga",
  price: "₩1,299,990",
  popularity: 25,
  new: 21,
      chipset: "  ",
  image: "./img/vga20.png",
  desc: [
      "GIGABYTE 지포스 RTX 4070 SUPER WINDFORCE OC D6X 12GB",
      "NVIDIA RTX 4070 SUPER",
      "PCIe4.0x16",
      "정격파워700W 이상",
      "전원 포트: 16핀(12VHPWR) x1",
      "가로(길이): 261mm",
      "부스트클럭: 2505MHz",
      "스트림 프로세서: 7168개",
      "GDDR6X",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "3팬",
      "두께: 50mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "A/S 3년"
  ]
},
"vga21": {
  name: "갤럭시 GALAX 지포스 RTX 4070 Ti EX GAMER WHITE OC V2 D6X 12GB",
  category: "vga",
  price: "₩1,375,500",
  popularity: 26,
  new: 24,
      chipset: "RTX 4070 Ti",
  image: "./img/vga21.png",
  desc: [
      "갤럭시 GALAX 지포스 RTX 4070 Ti EX GAMER WHITE OC V2 D6X 12GB",
      "NVIDIA RTX 4070 Ti",
      "PCIe4.0x16",
      "정격파워800W 이상",
      "전원 포트: 16핀(12VHPWR) x1",
      "가로(길이): 323mm",
      "베이스클럭: 2310MHz",
      "부스트클럭: 2670MHz",
      "스트림 프로세서: 7680개",
      "GDDR6X",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원",
      "사용전력: 최대 285W",
      "3팬",
      "두께: 60mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "XTREME TUNER",
      "구성품: VGA지지대, 2x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga22": {
  name: "ASUS TUF Gaming 지포스 RTX 4070 Ti SUPER BTF O16G OC D6X 16GB White",
  category: "vga",
  price: "₩1,488,990",
  popularity: 27,
  new: 7,
      chipset: "RTX 4070 Ti SUPER",
  image: "./img/vga22.png",
  desc: [
      "ASUS TUF Gaming 지포스 RTX 4070 Ti SUPER BTF O16G OC D6X 16GB White",
      "NVIDIA RTX 4070 Ti SUPER",
      "PCIe4.0x16",
      "정격파워750W 이상",
      "전원 포트: GC-HPWR 전용",
      "가로(길이): 305mm",
      "베이스클럭: 2340MHz",
      "부스트클럭: 2640MHz",
      "OC클럭: 2670MHz",
      "스트림 프로세서: 8448개",
      "GDDR6X",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "3팬",
      "두께: 65mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "AURA SYNC",
      "구성품: VGA지지대, 2x8핀 to 16핀 커넥터"
  ]
},"vga23": {
  name: "이엠텍 지포스 RTX 4060 STORM X Dual OC D6 8GB",
  category: "vga",
  price: "₩505,000",
  popularity: 28,
  new: 30,
      chipset: "RTX 4060",
  image: "./img/vga23.png",
  desc: [
      "이엠텍 지포스 RTX 4060 STORM X Dual OC D6 8GB",
      "NVIDIA RTX 4060",
      "PCIe4.0x16(at x8)",
      "정격파워600W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 249.9mm",
      "베이스클럭: 1830MHz",
      "부스트클럭: 2670MHz",
      "스트림 프로세서: 3072개",
      "GDDR6",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 115W",
      "2팬",
      "두께: 40.2mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "A/S 3년"
  ]
},
"vga24": {
  name: "이엠텍 지포스 RTX 4080 SUPER BLACK STORM OC D6X 16GB",
  category: "vga",
  price: "₩3,990,000",
  popularity: 29,
  new: 23,
      chipset: "RTX 4080 SUPER",
  image: "./img/vga24.png",
  desc: [
      "이엠텍 지포스 RTX 4080 SUPER BLACK STORM OC D6X 16GB",
      "NVIDIA RTX 4080 SUPER",
      "PCIe4.0x16",
      "정격파워850W 이상",
      "전원 포트: 16핀(12VHPWR) x1",
      "가로(길이): 328.9mm",
      "베이스클럭: 2295MHz",
      "부스트클럭: 2580MHz",
      "스트림 프로세서: 10240개",
      "GDDR6X",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 320W",
      "3팬",
      "두께: 63.5mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS",
      "구성품: 2x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga25": {
  name: "이엠텍 지포스 RTX 4060 Ti MIRACLE WHITE D6 8GB",
  category: "vga",
  price: "₩651,580",
  popularity: 30,
  new: 26,
      chipset: "RTX 4060 Ti",
  image: "./img/vga25.png",
  desc: [
      "이엠텍 지포스 RTX 4060 Ti MIRACLE WHITE D6 8GB",
      "NVIDIA RTX 4060 Ti",
      "PCIe4.0x16(at x8)",
      "정격파워650W 이상",
      "전원 포트: 8핀 x1",
      "가로(길이): 252mm",
      "베이스클럭: 2310MHz",
      "부스트클럭: 2535MHz",
      "스트림 프로세서: 4352개",
      "GDDR6",
      "출력단자: HDMI2.1, DP1.4",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "사용전력: 160W",
      "2팬",
      "두께: 42mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "DrMOS",
      "LED 라이트",
      "A/S 3년",
      "24년 11월부로 방열판 디자인 변경"
  ]
},
"vga26": {
  name: "GIGABYTE 지포스 RTX 5070 Ti WINDFORCE OC SFF D7 16GB",
  category: "vga",
  price: "₩1,369,050",
  popularity: 31,
  new: 12,
      chipset: "RTX 5070 Ti",
  image: "./img/vga26.png",
  desc: [
      "GIGABYTE 지포스 RTX 5070 Ti WINDFORCE OC SFF D7 16GB",
      "NVIDIA RTX 5070 Ti",
      "PCIe5.0x16",
      "정격파워750W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 304mm",
      "베이스클럭: 2295MHz",
      "부스트클럭: 2497MHz",
      "스트림 프로세서: 8960개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "3팬",
      "두께: 50mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "Dual BIOS",
      "구성품: VGA지지대, 2x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
},
"vga27": {
  name: "GIGABYTE AORUS 지포스 RTX 5090 MASTER D7 32GB 피씨디렉트",
  category: "vga",
  price: "₩5,199,000",
  popularity: 32,
  new: 7,
      chipset: "RTX 5090",
  image: "./img/vga27.png",
  desc: [
      "GIGABYTE AORUS 지포스 RTX 5090 MASTER D7 32GB 피씨디렉트",
      "NVIDIA RTX 5090",
      "PCIe5.0x16",
      "정격파워1000W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 360mm",
      "부스트클럭: 2655MHz",
      "스트림 프로세서: 21760개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원, HDR 지원, HDCP 2.3",
      "3+1팬",
      "두께: 75mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "Dual BIOS",
      "RGB FUSION",
      "구성품: VGA지지대, 4x8핀 to 16핀 커넥터, 후면 추가팬",
      "A/S 4년"
  ]
},
"vga28": {
  name: "GIGABYTE 지포스 RTX 5080 GAMING OC D7 16GB 피씨디렉트",
  category: "vga",
  price: "₩2,133,990",
  popularity: 33,
  new: 6,
      chipset: "RTX 5080",
  image: "./img/vga28.png",
  desc: [
      "GIGABYTE 지포스 RTX 5080 GAMING OC D7 16GB 피씨디렉트",
      "NVIDIA RTX 5080",
      "PCIe5.0x16",
      "정격파워850W 이상",
      "가로(길이): 340mm",
      "부스트클럭: 2730MHz",
      "스트림 프로세서: 10752개",
      "GDDR7",
      "출력단자: HDMI2.1, DP2.1",
      "지원정보: 8K 지원",
      "3팬",
      "두께: 70mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "LED 라이트",
      "Dual BIOS",
      "구성품: VGA지지대, 3x8핀 to 16핀 커넥터",
      "A/S 4년"
  ]
},
"vga29": {
  name: "ZOTAC GAMING 지포스 RTX 5070 AMP White D7 12GB",
  category: "vga",
  price: "₩985,790",
  popularity: 12.5, 
  new: 6.5,       
  chipset: "RTX 5070",
  image: "./img/vga29.png",
  desc: [
      "RTX 5070",
      "PCIe5.0x16",
      "정격파워650W 이상",
      "전원 포트: 16핀(12V2x6) x1",
      "가로(길이): 304.4mm",
      "베이스클럭: 2325MHz",
      "부스트클럭: 2587MHz",
      "스트림 프로세서: 6144개",
      "GDDR7",
      "출력단자: HDMI2.1 , DP2.1",
      "지원정보: 8K 지원 , HDR 지원 , HDCP 2.3",
      "사용전력: 250W",
      "전원부: 9+3페이즈",
      "3팬",
      "두께: 41.6mm",
      "제로팬(0-dB기술)",
      "백플레이트",
      "SPECTRA",
      "구성품: VGA지지대, 2x8핀 to 16핀 커넥터",
      "A/S 3년"
  ]
}




};

const cpuProducts = {
  "f": {
  name: "인텔 코어 울트라7 시리즈2 265K (애로우레이크)",
  category: "cpu",
  price: "₩539,990",
  popularity: 3,
  new: 5,
  image: "./img/product05.png",
  desc: [
      "인텔(소켓1851)",
      "20코어",
      "20스레드",
      "DDR5",
      "탑재 (인텔 그래픽스 Xe LPG)",
      "TSMC 3nm",
      "3.9GHz",
      "5.5GHz",
      "36MB",
      "30MB",
      "125-250W",
      "PCIe 5.0, PCIe 4.0",
      "6400MHz",
      "인텔 XTU, 인텔 딥러닝 부스트",
      "미포함",
      "2304점",
      "36309점",
      "$394 (VAT 별도)"
      ]
  },
  "g": {
      name: "AMD 라이젠7-6세대 9700X (그래니트 릿지)",
      category: "cpu",
      price: "₩474,040",
      popularity: 9,
      new: 3,
      image: "./img/product06.png",
      desc: [
          "AMD(소켓AM5)",
          "라이젠 9000",
          "8 코어 / 16스레드",
          "DDR5",
          "탑재 (AMD 라데온 그래픽)",
          "6세대(Zen 5)",
          "TSMC 4nm",
          "3.8GHz",
          "5.5GHz",
          "8MB",
          "32MB",
          "65W",
          "88W",
          "PCIe 5.0",
          "5600MHz",
          "SMT(하이퍼스레딩), AMD Ryzen Master",
          "미포함",
          "2260점",
          "21436점",
          "$359 (VAT 별도)"
      ]
  },
  "h": {
      name: "AMD 라이젠7-6세대 9800X3D (그래니트 릿지)",
      category: "cpu",
      price: "₩795,990",
      popularity: 1,
      new: 1,
      image: "./img/product07.png",
      desc: [
          "AMD(소켓AM5)",
          "라이젠 9000",
          "8 코어 / 16스레드",
          "DDR5",
          "탑재 (AMD 라데온 그래픽)",
          "6세대(Zen 5)",
          "TSMC 4nm",
          "3.8GHz",
          "5.5GHz",
          "8MB",
          "32MB",
          "65W",
          "88W",
          "PCIe 5.0",
          "5600MHz",
          "SMT(하이퍼스레딩), AMD Ryzen Master",
          "미포함",
          "2260점",
          "21436점",
          "$359 (VAT 별도)"
      ]
  },
  "i": {
  "name": "인텔 코어i7-14세대 14700K (랩터레이크 리프레시)",
  "category": "cpu",
  "price": "₩552,890",
  popularity: 10,
  new: 9,
  "image": "./img/product08.png",
  "desc": [
      "인텔(소켓1700)",
      "20코어" ,
      "28스레드",
      "DDR5, DDR4",
      "탑재 (인텔 UHD 770)",
      "인텔 7 (10nm)",
      "3.4GHz",
      "5.6GHz",
      "28MB",
      "33MB",
      "125-253W",
      "PCIe 5.0, PCIe 4.0",
      "5600MHz, 3200MHz",
      "SMT(하이퍼스레딩), 인텔 XTU, 인텔 퀵싱크, 인텔 딥러닝부스트",
      "미포함",
      "2069점",
      "34818점",
      "$409 (VAT 별도)"
  ]
},

  "j": {
      name: "인텔 코어 울트라5 시리즈2 225F (애로우레이크)",
      category: "cpu",
      price: "₩326,990",
      popularity: 21,
      new: 13,
      image: "./img/product09.png",
      desc: [
          "인텔(소켓1851)",
          "10코어",
          "10스레드",
          "DDR5",
          "미탑재",
          "TSMC 3nm",
          "3.3GHz",
          "4.9GHz",
          "22MB",
          "20MB",
          "65W",
          "121W",
          "PCIe 5.0, 4.0",
          "6400MHz",
          "인텔 딥러닝부스트",
          "인텔 기본쿨러 포함",
          "$221 (VAT 별도)"
      ]
    },        
        "cpu1": {
          "name": "인텔 코어i5-14세대 14400F (랩터레이크 리프레시)",
          "category": "cpu",
          "price": "₩185,060",
          popularity: 13,
          new: 11,
          "image": "./img/cpu1.png",
          "desc": [
            "인텔(소켓1700)",
            "10코어",
            "16스레드",
            "메모리 규격: DDR5, DDR4",
            "내장그래픽:미탑재",
            "10nm(인텔7)",
            "기본 클럭: 2.5GHz",
            "최대 클럭: 4.7GHz",
            "L2 캐시: 9.5MB",
            "L3 캐시: 20MB",
            "PBP-MTP: 65-148W",
            "PCIe5.0, 4.0",
            "4800, 3200MHz",
            "기술 지원: SMT(하이퍼스레딩), 인텔 딥러닝부스트",
            "쿨러: 인텔 기본쿨러 포함",
            "시네벤치R23(싱글): 1790",
            "시네벤치R23(멀티): 17804"
          ]
        },
        "cpu2": {
          "name": "인텔 코어i5-14세대 14600KF (랩터레이크 리프레시)",
          "category": "cpu",
          "price": "₩276,240",
          popularity: 6,
          new: 10,
          "image": "./img/cpu2.png",
          "desc": [
            "인텔(소켓1700)",
            "14코어",
            "20스레드",
            "메모리 규격: DDR5, DDR4",
            "내장그래픽:미탑재",
            "10nm(인텔7)",
            "기본 클럭: 3.5GHz",
            "최대 클럭: 5.3GHz",
            "L2 캐시: 20MB",
            "L3 캐시: 24MB",
            "PBP-MTP: 125-181W",
            "PCIe5.0, 4.0",
            "5600, 3200MHz",
            "기술 지원: SMT(하이퍼스레딩), 인텔 XTU, 인텔 퀵싱크, 인텔 딥러닝부스트",
            "쿨러: 미포함",
            "시네벤치R23(싱글): 2054",
            "시네벤치R23(멀티): 24086"
          ]
        },
        "cpu3": {
          "name": "인텔 코어 울트라9 시리즈2 285K (애로우레이크)",
          "category": "cpu",
          "price": "₩907,850",
          popularity: 8,
          new: 4,
          "image": "./img/cpu3.png",
          "desc": [
            "인텔(소켓1851)",
            "24코어",
            "24스레드",
            "메모리 규격: DDR5",
            "내장그래픽:탑재",
            "TSMC 3nm",
            "기본 클럭: 3.7GHz",
            "최대 클럭: 5.7GHz",
            "L2 캐시: 40MB",
            "L3 캐시: 36MB",
            "PBP-MTP: 125-250W",
            "PCIe5.0, 4.0",
            "6400MHz",
            "인텔 그래픽스(Xe LPG)",
            "기술 지원: 인텔 XTU, 인텔 딥러닝부스트",
            "쿨러: 미포함",
            "시네벤치R23(싱글): 2320",
            "시네벤치R23(멀티): 41558",
            "출시가: 589달러(VAT별도)"
          ]
        },
        "cpu4": {
          "name": "인텔 코어i5-14세대 14600K (랩터레이크 리프레시)",
          "category": "cpu",
          "price": "₩332,390",
          popularity: 15,
          new: 12,
          "image": "./img/cpu4.png",
          "desc": [
            "인텔(소켓1700)",
            "14코어",
            "20스레드",
            "메모리 규격: DDR5, DDR4",
            "내장그래픽:탑재",
            "10nm(인텔7)",
            "기본 클럭: 3.5GHz",
            "최대 클럭: 5.3GHz",
            "L2 캐시: 20MB",
            "L3 캐시: 24MB",
            "PBP-MTP: 125-181W",
            "PCIe5.0, 4.0",
            "5600, 3200MHz",
            "인텔 UHD 770",
            "기술 지원: SMT(하이퍼스레딩), 인텔 XTU, 인텔 퀵싱크, 인텔 딥러닝부스트",
            "쿨러: 미포함",
            "시네벤치R23(싱글): 2069",
            "시네벤치R23(멀티): 25159",
            "출시가: 319달러 (VAT별도)"
          ]
        },
        "cpu5": {
          "name": "인텔 코어 울트라7 시리즈2 265KF (애로우레이크)",
          "category": "cpu",
          "price": "₩445,160",
          popularity: 11,
          new: 6,
          "image": "./img/cpu5.png",
          "desc": [
            "인텔(소켓1851)",
            "20코어",
            "20스레드",
            "메모리 규격: DDR5",
            "내장그래픽:미탑재",
            "TSMC 3nm",
            "기본 클럭: 3.9GHz",
            "최대 클럭: 5.5GHz",
            "L2 캐시: 36MB",
            "L3 캐시: 30MB",
            "PBP-MTP: 125-250W",
            "PCIe5.0, 4.0",
            "6400MHz",
            "기술 지원: 인텔 XTU, 인텔 딥러닝부스트",
            "쿨러: 미포함",
            "시네벤치R23(싱글): 2309",
            "시네벤치R23(멀티): 37278",
            "출시가: 379달러(VAT별도)"
          ]
        },
        "cpu6": {
          "name": "인텔 코어i7-14세대 14700F (랩터레이크 리프레시)",
          "category": "cpu",
          "price": "₩440,840",
          popularity: 18,
          new: 8,
          "image": "./img/cpu6.png",
          "desc": [
            "인텔(소켓1700)",
            "20코어",
            "28스레드",
            "메모리 규격: DDR5, DDR4",
            "내장그래픽:미탑재",
            "10nm(인텔7)",
            "기본 클럭: 2.1GHz",
            "최대 클럭: 5.4GHz",
            "L2 캐시: 28MB",
            "L3 캐시: 33MB",
            "PBP-MTP: 65-219W",
            "PCIe5.0, 4.0",
            "5600, 3200MHz",
            "기술 지원: SMT(하이퍼스레딩), 인텔 XTU, 인텔 퀵싱크, 인텔 딥러닝부스트",
            "쿨러: 인텔 기본쿨러 포함",
            "시네벤치R23(싱글): 2091",
            "시네벤치R23(멀티): 32090",
            "출시가: 359달러 (VAT별도)"
          ]
        },
        "cpu7": {
          "name": "인텔 코어i7-14세대 14700KF (랩터레이크 리프레시)",
          "category": "cpu",
          "price": "₩471,360",
          popularity: 16,
          new: 7,
          "image": "./img/cpu7.png",
          "desc": [
            "인텔(소켓1700)",
            "20코어",
            "28스레드",
            "메모리 규격: DDR5, DDR4",
            "내장그래픽:미탑재",
            "10nm(인텔7)",
            "기본 클럭: 3.4GHz",
            "최대 클럭: 5.6GHz",
            "L2 캐시: 28MB",
            "L3 캐시: 33MB",
            "PBP-MTP: 125-253W",
            "PCIe5.0, 4.0",
            "5600, 3200MHz",
            "기술 지원: SMT(하이퍼스레딩), 인텔 XTU, 인텔 퀵싱크, 인텔 딥러닝부스트",
            "쿨러: 미포함",
            "시네벤치R23(싱글): 2145",
            "시네벤치R23(멀티): 35218",
            "출시가: 384달러 (VAT별도)"
          ]
        },
        "cpu8": {
          "name": "인텔 코어i5-13세대 13400F (랩터레이크)",
          "category": "cpu",
          "price": "₩188,640",
          popularity: 22,
          new: 21,
          "image": "./img/cpu8.png",
          "desc": [
            "인텔(소켓1700)",
            "10코어",
            "16스레드",
            "메모리 규격: DDR5, DDR4",
            "내장그래픽:미탑재",
            "10nm(인텔7)",
            "기본 클럭: 2.5GHz",
            "최대 클럭: 4.6GHz",
            "L2 캐시: 9.5MB",
            "L3 캐시: 20MB",
            "PBP-MTP: 65-148W",
            "PCIe5.0, 4.0",
            "4800, 3200MHz",
            "기술 지원: SMT(하이퍼스레딩), 인텔 XTU, 인텔 퀵싱크, 인텔 딥러닝부스트",
            "쿨러: 인텔 기본쿨러 포함",
            "시네벤치R23(싱글): 1789",
            "시네벤치R23(멀티): 14621",
            "출시가: 196달러 (VAT별도)"
          ]
        },
        "cpu9": {
          "name": "인텔 코어 울트라5 시리즈2 235 (애로우레이크)",
          "category": "cpu",
          "price": "₩379,650",
          popularity: 23,
          new: 14,
          "image": "./img/cpu9.png",
          "desc": [
            "인텔(소켓1851)",
            "14코어",
            "14스레드",
            "메모리 규격: DDR5",
            "내장그래픽:탑재",
            "TSMC 3nm",
            "기본 클럭: 3.4GHz",
            "최대 클럭: 5.0GHz",
            "L2 캐시: 26MB",
            "L3 캐시: 24MB",
            "PBP-MTP: 65-121W",
            "PCIe5.0, 4.0",
            "6400MHz",
            "인텔 그래픽스(Xe LPG)",
            "기술 지원: 인텔 딥러닝부스트",
            "쿨러: 인텔 기본쿨러 포함",
            "출시가: 247달러(VAT별도)"
          ]
        },
        "cpu10": {
          "name": "인텔 코어 울트라5 시리즈2 245K (애로우레이크)",
          "category": "cpu",
          "price": "₩411,060",
          popularity: 24,
          new: 15,
          "image": "./img/cpu10.png",
          "desc": [
            "인텔(소켓1851)",
            "14코어",
            "14스레드",
            "메모리 규격: DDR5",
            "내장그래픽:탑재",
            "TSMC 3nm",
            "기본 클럭: 4.2GHz",
            "최대 클럭: 5.2GHz",
            "L2 캐시: 26MB",
            "L3 캐시: 24MB",
            "PBP-MTP: 125-159W",
            "PCIe5.0, 4.0",
            "6400MHz",
            "인텔 그래픽스(Xe LPG)",
            "기술 지원: 인텔 XTU, 인텔 딥러닝부스트",
            "쿨러: 미포함",
            "시네벤치R23(싱글): 2114",
            "시네벤치R23(멀티): 24935",
            "출시가: 309달러(VAT별도)"
          ]
        },          
          "cpu11": {
            "name": "AMD 라이젠9-6세대 9950X3D (그래니트 릿지)",
            "category": "cpu",
            "price": "₩1,149,000",
            popularity: 7,
            new: 16,
            "image": "./img/cpu11.png",
            "desc": [
              "AMD(소켓AM5)",
              "라이젠 9000",
              "16코어 / 32스레드",
              "DDR5",
              "탑재 (AMD 라데온 그래픽)",
              "6세대(Zen5)",
              "TSMC 4nm",
              "4.3GHz",
              "5.7GHz",
              "16MB",
              "128MB",
              "170W",
              "PCIe 5.0",
              "5600MHz",
              "SMT(하이퍼스레딩), AMD Ryzen Master, AMD 3D V캐시",
              "미포함",
              "출시가: 699달러(VAT별도)"
            ]
          },
          "cpu12": {
            "name": "AMD 라이젠7-5세대 7700 (라파엘)",
            "category": "cpu",
            "price": "₩350,660",
            popularity: 17,
            new: 23,
            "image": "./img/cpu12.png",
            "desc": [
              "AMD(소켓AM5)",
              "라이젠 7000",
              "8 코어 / 16스레드",
              "DDR5",
              "탑재 (AMD 라데온 그래픽)",
              "5세대(Zen4)",
              "5nm",
              "3.8GHz",
              "5.3GHz",
              "8MB",
              "32MB",
              "65W",
              "PPT: 88W",
              "PCIe 5.0",
              "5200MHz",
              "SMT(하이퍼스레딩)",
              "Wraith PRISM 포함",
              "시네벤치R23(싱글): 1933",
              "시네벤치R23(멀티): 18854"
            ]
          },
          "cpu13": {
            "name": "AMD 라이젠5-5세대 7500F (라파엘)",
            "category": "cpu",
            "price": "₩209,520",
            popularity: 2,
            new: 24,
            "image": "./img/cpu13.png",
            "desc": [
              "AMD(소켓AM5)",
              "라이젠 7000",
              "6 코어 / 12스레드",
              "DDR5",
              "미탑재",
              "5세대(Zen4)",
              "5nm",
              "3.7GHz",
              "5.0GHz",
              "6MB",
              "32MB",
              "65W",
              "PPT: 88W",
              "PCIe 5.0",
              "5200MHz",
              "SMT(하이퍼스레딩)",
              "Wraith Stealth 포함",
              "시네벤치R23(싱글): 1824",
              "시네벤치R23(멀티): 13824",
              "출시가: 179달러(VAT별도)"
            ]
          },
          "cpu14": {
            "name": "AMD 라이젠5-5세대 7600X (라파엘)",
            "category": "cpu",
            "price": "₩279,000",
            popularity: 25,
            new: 22,
            "image": "./img/cpu14.png",
            "desc": [
              "AMD(소켓AM5)",
              "라이젠 7000",
              "6 코어 / 12스레드",
              "DDR5",
              "탑재 (AMD 라데온 그래픽)",
              "5세대(Zen4)",
              "5nm",
              "4.7GHz",
              "5.3GHz",
              "6MB",
              "32MB",
              "105W",
              "PPT: 142W",
              "PCIe 5.0",
              "5200MHz",
              "SMT(하이퍼스레딩)",
              "미포함",
              "시네벤치R23(싱글): 1961",
              "시네벤치R23(멀티): 15215"
            ]
          },
          "cpu15": {
            "name": "AMD 라이젠9-5세대 7950X (라파엘)",
            "category": "cpu",
            "price": "₩596,000",
            popularity: 19,
            new: 20,
            "image": "./img/cpu15.png",
            "desc": [
              "AMD(소켓AM5)",
              "라이젠 7000",
              "16코어 / 32스레드",
              "DDR5",
              "탑재 (AMD 라데온 그래픽)",
              "5세대(Zen4)",
              "5nm",
              "4.5GHz",
              "5.7GHz",
              "16MB",
              "64MB",
              "170W",
              "PPT: 230W",
              "PCIe 5.0",
              "5200MHz",
              "SMT(하이퍼스레딩)",
              "미포함",
              "시네벤치R23(싱글): 2025",
              "시네벤치R23(멀티): 36836"
            ]
          },
          "cpu16": {
            "name": "AMD 라이젠5-4세대 5600 (버미어)",
            "category": "cpu",
            "price": "₩122,640",
            popularity: 4,
            new: 29,
            "image": "./img/cpu16.png",
            "desc": [
              "AMD(소켓AM4)",
              "라이젠 5000",
              "6 코어 / 12스레드",
              "DDR4",
              "미탑재",
              "4세대(Zen3)",
              "7nm",
              "3.5GHz",
              "4.4GHz",
              "3MB",
              "32MB",
              "65W",
              "PCIe 4.0",
              "3200MHz",
              "SMT(하이퍼스레딩), StoreMI, AMD Ryzen Master, VR Ready 프리미엄",
              "Wraith Stealth 포함",
              "시네벤치R23(싱글): 1460",
              "시네벤치R23(멀티): 10906",
              "출시가: 199달러(VAT별도)"
            ]
          },
          "cpu17": {
            "name": "AMD 라이젠7-4세대 5700X (버미어)",
            "category": "cpu",
            "price": "₩211,940",
            popularity: 12,
            new: 28,
            "image": "./img/cpu17.png",
            "desc": [
              "AMD(소켓AM4)",
              "라이젠 5000",
              "8 코어 / 16스레드",
              "DDR4",
              "미탑재",
              "4세대(Zen3)",
              "7nm",
              "3.4GHz",
              "4.6GHz",
              "4MB",
              "32MB",
              "65W",
              "PCIe 4.0",
              "3200MHz",
              "SMT(하이퍼스레딩), StoreMI, AMD Ryzen Master, VR Ready 프리미엄",
              "미포함",
              "시네벤치R23(싱글): 1527",
              "시네벤치R23(멀티): 13293",
              "출시가: 299달러(VAT별도)"
            ]
          },
          "cpu18": {
            "name": "AMD 라이젠7-4세대 5700X3D (버미어)",
            "category": "cpu",
            "price": "₩559,000",
            popularity: 20,
            new: 27,
            "image": "./img/cpu18.png",
            "desc": [
              "AMD(소켓AM4)",
              "라이젠 5000",
              "8 코어 / 16스레드",
              "DDR4",
              "미탑재",
              "4세대(Zen3)",
              "7nm",
              "3.0GHz",
              "4.1GHz",
              "4MB",
              "96MB",
              "105W",
              "PPT: 142W",
              "PCIe 4.0",
              "3200MHz",
              "SMT(하이퍼스레딩), StoreMI, AMD Ryzen Master, VR Ready 프리미엄, AMD 3D V캐시",
              "미포함",
              "시네벤치R23(싱글): 1367",
              "시네벤치R23(멀티): 13788"
            ]
          },
          "cpu19": {
            "name": "AMD 라이젠7-4세대 5800X (버미어)",
            "category": "cpu",
            "price": "₩480,800",
            popularity: 26,
            new: 26,
            "image": "./img/cpu19.png",
            "desc": [
              "AMD(소켓AM4)",
              "라이젠 5000",
              "8 코어 / 16스레드",
              "DDR4",
              "미탑재",
              "4세대(Zen3)",
              "7nm",
              "3.8GHz",
              "4.7GHz",
              "4MB",
              "32MB",
              "105W",
              "PCIe 4.0",
              "3200MHz",
              "SMT(하이퍼스레딩), StoreMI, AMD Ryzen Master, VR Ready 프리미엄",
              "미포함",
              "시네벤치R23(싱글): 1593",
              "시네벤치R23(멀티): 15416"
            ]
          },
          "cpu20": {
            "name": "AMD 라이젠9-6세대 9900X3D (그래니트 릿지)",
            "category": "cpu",
            "price": "₩887,460",
            popularity: 14,
            new: 17,
            "image": "./img/cpu20.png",
            "desc": [
              "AMD(소켓AM5)",
              "라이젠 9000",
              "12코어 / 24스레드",
              "DDR5",
              "탑재 (AMD 라데온 그래픽)",
              "6세대(Zen5)",
              "TSMC 4nm",
              "4.4GHz",
              "5.5GHz",
              "12MB",
              "128MB",
              "120W",
              "PCIe 5.0",
              "5600MHz",
              "SMT(하이퍼스레딩), AMD Ryzen Master, AMD 3D V캐시",
              "미포함",
              "출시가: 599달러(VAT별도)"
            ]
          },
          "cpu21": {
            "name": "인텔 코어i9-13세대 13900F (랩터레이크)",
            "category": "cpu",
            "price": "₩720,120",
            popularity: 27,
            new: 20,
            "image": "./img/cpu21.png",
            "desc": [
              "인텔(소켓1700)",
              "24코어 / 32스레드",
              "DDR5, DDR4",
              "미탑재",
              "10nm(인텔7)",
              "기본 클럭: 2.0GHz",
              "최대 클럭: 5.6GHz",
              "L2 캐시: 32MB",
              "L3 캐시: 36MB",
              "PBP-MTP: 65-219W",
              "PCIe5.0, 4.0",
              "5600, 3200MHz",
              "SMT(하이퍼스레딩), 인텔 XTU, 인텔 퀵싱크, 인텔 딥러닝부스트",
              "인텔 기본쿨러 포함",
              "시네벤치R23(싱글): 2180",
              "시네벤치R23(멀티): 37135",
              "출시가: 524~554달러 (VAT별도)"
            ]
          },
          "cpu22": {
            "name": "인텔 코어i9-12세대 12900K (엘더레이크)",
            "category": "cpu",
            "price": "₩599,200",
            popularity: 28,
            new: 30,
            "image": "./img/cpu22.png",
            "desc": [
              "인텔(소켓1700)",
              "16코어 / 24스레드",
              "DDR5, DDR4",
              "탑재 (인텔 UHD 770)",
              "10nm(인텔7)",
              "기본 클럭: 3.2GHz",
              "최대 클럭: 5.2GHz",
              "L2 캐시: 14MB",
              "L3 캐시: 30MB",
              "TDP: 125~241W",
              "PCIe5.0, 4.0",
              "4800, 3200MHz",
              "SMT(하이퍼스레딩), 옵테인",
              "미포함",
              "시네벤치R23(싱글): 2044",
              "시네벤치R23(멀티): 27746",
              "출시가: 589~599달러(VAT별도)"
            ]
          },
          "cpu23": {
            "name": "인텔 코어i9-12세대 12900 (엘더레이크)",
            "category": "cpu",
            "price": "₩644,000",
            popularity: 29,
            new: 31,
            "image": "./img/cpu23.png",
            "desc": [
              "인텔(소켓1700)",
              "16코어 / 24스레드",
              "DDR5, DDR4",
              "탑재 (인텔 UHD 770)",
              "10nm(인텔7)",
              "기본 클럭: 2.4GHz",
              "최대 클럭: 5.1GHz",
              "L2 캐시: 14MB",
              "L3 캐시: 30MB",
              "TDP: 65~202W",
              "PCIe5.0, 4.0",
              "4800, 3200MHz",
              "SMT(하이퍼스레딩), 인텔 딥러닝부스트, 옵테인",
              "인텔 기본쿨러 포함",
              "출시가: 489달러 (VAT별도)"
            ]
          },
          "cpu24": {
            "name": "인텔 코어i9-13세대 13900K (랩터레이크)",
            "category": "cpu",
            "price": "₩880,770",
            popularity: 24,
            new: 18,
            "image": "./img/cpu24.png",
            "desc": [
              "인텔(소켓1700)",
              "24코어 / 32스레드",
              "DDR5, DDR4",
              "탑재 (인텔 UHD 770)",
              "10nm(인텔7)",
              "기본 클럭: 3.0GHz",
              "최대 클럭: 5.8GHz",
              "L2 캐시: 32MB",
              "L3 캐시: 36MB",
              "PBP-MTP: 125-253W",
              "PCIe5.0, 4.0",
              "5600, 3200MHz",
              "SMT(하이퍼스레딩), 인텔 XTU, 인텔 딥러닝부스트",
              "미포함",
              "시네벤치R23(싱글): 2251",
              "시네벤치R23(멀티): 38207",
              "출시가: 589달러 (VAT별도)"
            ]
          },
          "cpu25": {
            "name": "인텔 코어i9-13세대 13900KF (랩터레이크)",
            "category": "cpu",
            "price": "₩846,050",
            popularity: 30,
            new: 19,
            "image": "./img/cpu25.png",
            "desc": [
              "인텔(소켓1700)",
              "24코어 / 16스레드",
              "DDR5, DDR4",
              "미탑재",
              "10nm(인텔7)",
              "기본 클럭: 3.0GHz",
              "최대 클럭: 5.8GHz",
              "L2 캐시: 32MB",
              "L3 캐시: 36MB",
              "PBP-MTP: 125-253W",
              "PCIe5.0, 4.0",
              "5600, 3200MHz",
              "SMT(하이퍼스레딩), 인텔 XTU, 인텔 딥러닝부스트",
              "미포함",
              "시네벤치R23(싱글): 2258",
              "시네벤치R23(멀티): 38753",
              "출시가: 564달러 (VAT별도)"
            ]
          },
          "cpu26": {
            "name": "인텔 코어 울트라9 시리즈2 285 (애로우레이크)",
            "category": "cpu",
            "price": "₩852,160",              
            popularity: 31,
            new: 3,
            "image": "./img/cpu26.png",
            "desc": [
              "인텔(소켓1851)",
              "P8+E16코어",
              "24스레드",
              "메모리 규격: DDR5",
              "내장그래픽:탑재",
              "TSMC 3nm",
              "기본 클럭: 2.5GHz",
              "최대 클럭: 5.6GHz",
              "L2 캐시: 40MB",
              "L3 캐시: 36MB",
              "PBP-MTP: 65-182W",
              "PCIe5.0, 4.0",
              "6400MHz",
              "인텔 그래픽스(Xe LPG)",
              "기술 지원: 인텔 딥러닝부스트",
              "쿨러: 인텔 기본쿨러 포함",
              "출시가: 549달러(VAT별도)"
            ]
          },

};         

const coolerProducts = {
  "cooler1": {
    name: "DEEPCOOL AG400",
    category: "cooler",
    price: "₩21,760",
    image: "./img/cooler1.png",
    desc: [
      "공랭, 싱글타워형, 팬 쿨러",
      "TDP: 220W",
      "A/S 기간: 1년",
      "인텔 소켓: LGA1851, LGA1700, LGA1200, LGA115x",
      "AMD 소켓: AM5, AM4",
      "크기: 125 x 92 x 150mm",
      "무게: 614g",
      "팬 크기: 120mm",
      "팬 개수: 1개",
      "팬 두께: 25T",
      "팬 커넥터: 4핀",
      "베어링: Hydro(유체)",
      "최대 RPM: 2000 RPM",
      "최대 풍량: 75.89 CFM",
      "풍압(정압): 2.53mmH₂O",
      "최대 팬소음: 31.6dBA",
      "PWM 지원: 지원",
      "LED: non-LED",
      "24년 11월부로 1851소켓 지원 추가"
    ]
  },

  "cooler2": {
    name: "PCCOOLER PALADIN 400",
    category: "cooler",
    price: "₩24,630",
    image: "./img/cooler2.png",
    desc: [
      "공랭, 싱글타워형, 팬 쿨러",
      "TDP: 200W",
      "A/S 기간: 3년",
      "인텔 소켓: LGA1851, LGA1700, LGA1200, LGA115x",
      "AMD 소켓: AM5, AM4",
      "크기: 130 x 76 x 157mm",
      "무게: 700g",
      "팬 크기: 130mm",
      "팬 개수: 1개",
      "팬 두께: 25T",
      "팬 커넥터: 4핀",
      "베어링: Hydraulic(유체)",
      "최대 RPM: 1600 RPM",
      "최대 풍량: 81 CFM",
      "풍압(정압): 2.18mmH₂O",
      "최대 팬소음: 28.6dBA",
      "PWM 지원: 지원",
      "LED: non-LED",
      "AM4이탈방지가이드, 24년 11월 AM4 세이프가드 재추가, 12월 AS기간 확대 및 1851소켓지원 추가"
    ]
  },

  "cooler3": {
    name: "Thermalright Peerless Assassin 120 SE 서린",
    category: "cooler",
    price: "₩36,178",
    image: "./img/cooler3.png",
    desc: [
      "공랭, 듀얼타워형, 팬 쿨러",
      "TDP: 260W",
      "A/S 기간: 3년",
      "인텔 소켓: LGA1700, LGA1200, LGA115x",
      "AMD 소켓: AM5, AM4",
      "크기: 125 x 135 x 155mm",
      "무게: 850g",
      "팬 크기: 120mm",
      "팬 개수: 2개",
      "팬 두께: 25T",
      "팬 커넥터: 4핀",
      "베어링: S-FDB(유체)",
      "최대 RPM: 1550 RPM",
      "최대 풍량: 66.17 CFM",
      "풍압(정압): 1.53mmH₂O",
      "최대 팬소음: 25.6dBA",
      "PWM 지원: 지원",
      "LED: non-LED",
      "써멀컴파운드(주사기형), 열전도율 12.8W/(m·K), 23년 11월 AM5 소켓 호환 추가"
    ]
  },

  "cooler4": {
    name: "잘만 Alpha II A36",
    category: "cooler",
    price: "₩121,800",
    image: "./img/cooler4.png",
    desc: [
      "수랭, 팬 쿨러",
      "TDP: 350W",
      "A/S 기간: 5년+누수보상",
      "인텔 소켓: LGA1851, LGA1700, LGA1200, LGA115x",
      "AMD 소켓: AM5, AM4",
      "라디에이터: 3열, 길이 397mm, 두께 27mm",
      "호스 길이: 400mm",
      "팬 크기: 120mm",
      "팬 개수: 3개",
      "팬 두께: 25T",
      "팬 커넥터: 3-4핀",
      "베어링: Hydro(유체)",
      "최대 RPM: 2000 RPM",
      "최대 풍량: 69.12 CFM",
      "풍압(정압): 2.01mmH₂O",
      "최대 팬소음: 29.7dBA",
      "작동전압: 팬 12V, LED 5V",
      "LED: RGB, LED 라이트, 워터블록/로고 회전, 인디케이터",
      "LED 시스템: AURA SYNC, MYSTIC LIGHT, RGB FUSION, POLYCHROME",
      "PWM 지원: 지원",
      "써멀컴파운드(주사기형), 24년 12월 1851소켓 지원 추가"
    ]
  },

  "cooler5": {
    name: "3RSYS Socoool RC1900N 솔더링",
    category: "cooler",
    price: "₩72,590",
    image: "./img/cooler5.png",
    desc: [
      "공랭, 듀얼타워형, 팬 쿨러",
      "TDP: 280W",
      "A/S 기간: 3년",
      "인텔 소켓: LGA1700, LGA1200, LGA115x",
      "AMD 소켓: AM5, AM4",
      "크기: 132 x 140 x 157mm",
      "팬 크기: 130mm, 120mm",
      "팬 개수: 2개",
      "팬 두께: 25T, 28T",
      "팬 커넥터: 4핀",
      "베어링: FDB(유체)",
      "최대 RPM: 1600 RPM, 2200 RPM",
      "최대 풍량: 85 CFM, 70CFM",
      "풍압(정압): 2.0mmH₂O, 3.5mmH₂O",
      "최대 팬소음: 30dBA",
      "작동전압: 팬 12V",
      "PWM 지원: 지원",
      "LED: non-LED",
      "써멀컴파운드(주사기형), 열전도율 12.4W/(m·K), 25년 2월 제품 디자인 변경"
    ]
  }
};

const motherboardProducts = {
      "motherboard1": {
        name: "ASUS TUF Gaming B850M-PLUS WIFI STCOM",
        category: "motherboard",
        price: "₩278,860",
        image: "./img/motherboard1.png",
        desc: [
          "AMD(소켓AM5), AMD B850, DDR5",
          "VGA 연결: PCIe5.0 x16",
          "M-ATX (24.4x24.4cm)",
          "전원부: 14+2+1페이즈 (페이즈당 80A, Vcore 출력합계 1120A)",
          "메모리: 8000MHz (PC5-64000), 4개, 최대 192GB, XMP, EXPO",
          "확장슬롯: PCIe5.0, PCIe4.0 / PCIex16: 1개 / PCIex16(at x8): 1개 / PCIex1: 1개",
          "저장장치: M.2 3개(PCIe5.0/4.0/NVMe/PCIe 레인공유), SATA3 4개",
          "후면단자: HDMI, DP, USB3.x 20Gbps/10Gbps/5Gbps, USB 2.0, RJ-45, 오디오잭, BIOS플래시백",
          "USB A타입: 11개, USB C타입: 1개",
          "유선랜: Realtek 2.5Gbps, RJ-45 1개",
          "무선랜(Wi-Fi), 블루투스",
          "오디오: Realtek ALC1220P, 7.1채널(8ch)",
          "내부I/O: USB3.0/2.0 헤더, USB3.1 Type C 헤더, CPU추가팬(OPT) 헤더, 펌프전용 헤더, 시스템팬 4핀 3개, 프론트오디오AAFP 헤더, 침입감지 헤더, COM포트 헤더",
          "특징: DrMOS, 전원부 방열판, M.2 히트싱크, 일체형IO실드, LED라이트, UEFI"
        ]
      },
    
      "motherboard2": {
        name: "GIGABYTE B650M K 제이씨현",
        category: "motherboard",
        price: "₩142,830",
        image: "./img/motherboard2.png",
        desc: [
          "AMD(소켓AM5), AMD B650, DDR5",
          "VGA 연결: PCIe4.0 x16",
          "M-ATX (24.4x24.4cm)",
          "전원부: 8+2+2페이즈",
          "메모리: 8000MHz (PC5-64000), 4개, 최대 192GB, XMP3.0, EXPO",
          "확장슬롯: PCIe4.0, PCIe3.0 / PCIex16: 1개 / PCIex1: 1개",
          "저장장치: M.2 2개(PCIe4.0/NVMe), SATA3 4개",
          "후면단자: HDMI, DP, USB3.x 10Gbps/5Gbps, USB 2.0, RJ-45, 오디오잭, PS/2, BIOS플래시백",
          "USB A타입: 7개, USB C타입: 1개",
          "유선랜: Realtek 2.5Gbps, RJ-45 1개",
          "오디오: Realtek, 7.1채널(8ch)",
          "내부I/O: USB3.0/2.0 헤더, USB3.0 Type C 헤더, RGB 12V 4핀 헤더, ARGB 5V 3핀 헤더, 시스템팬 4핀 2개, TPM 헤더, 프론트오디오AAFP 헤더",
          "특징: 전원부 방열판, M.2 히트싱크, UEFI, 23년 12월 Rev 1.1 변경(전원부, 메모리, ARGB헤더 변경)"
        ]
      },
    
      "motherboard3": {
        name: "ASUS TUF Gaming B760M-PLUS II 코잇",
        category: "motherboard",
        price: "₩182,390",
        image: "./img/motherboard3.png",
        desc: [
          "인텔 B760, 인텔(소켓1700), DDR5",
          "VGA 연결: PCIe5.0 x16",
          "M-ATX (24.4x24.4cm)",
          "전원부: 12+1+1페이즈 (페이즈당 50A, Vcore 출력합계 600A)",
          "메모리: 7800MHz (PC5-62400), 4개, 최대 192GB, XMP",
          "확장슬롯: PCIe5.0/4.0/3.0 / PCIex16: 1개 / PCIex4: 1개 / PCIex1: 1개",
          "저장장치: M.2 3개(PCIe4.0/NVMe), SATA3 4개",
          "후면단자: HDMI, DP, USB3.x 20Gbps/10Gbps/5Gbps, USB 2.0, RJ-45, S/PDIF, 오디오잭",
          "USB A타입: 7개, USB C타입: 1개",
          "유선랜: Realtek 2.5Gbps, RJ-45 1개",
          "오디오: Realtek, 7.1채널(8ch)",
          "내부I/O: 썬더볼트4 헤더, USB4 헤더, USB3.0/2.0 헤더, USB3.1 Type C 헤더, RGB 12V 4핀 헤더, ARGB 5V 3핀 헤더, CPU추가팬(OPT) 헤더, 펌프전용 헤더, 시스템팬 4핀 3개, 디버그LED, 프론트오디오AAFP 헤더, 침입감지 헤더",
          "특징: DrMOS, 전원부 방열판, M.2 히트싱크, UEFI"
        ]
      },
    
      "motherboard4": {
        name: "MSI MAG B760M 박격포 II",
        category: "motherboard",
        price: "₩184,970",
        image: "./img/motherboard4.png",
        desc: [
          "인텔 B760, 인텔(소켓1700), DDR5",
          "VGA 연결: PCIe5.0 x16",
          "M-ATX (24.4x24.4cm)",
          "전원부: 12+1+1페이즈 (페이즈당 75A, Vcore 출력합계 900A)",
          "메모리: 7800MHz (PC5-62400), 4개, 최대 256GB, XMP3.0",
          "확장슬롯: PCIe5.0/3.0 / PCIex16: 1개 / PCIex4: 1개",
          "저장장치: M.2 3개(PCIe4.0/NVMe/SATA), SATA3 4개",
          "후면단자: HDMI, DP, USB3.x 20Gbps/10Gbps, USB 2.0, RJ-45, S/PDIF, 오디오잭",
          "USB A타입: 7개, USB C타입: 1개",
          "유선랜: Realtek 8125BG 2.5Gbps, RJ-45 1개",
          "오디오: Realtek ALC897, 7.1채널(8ch)",
          "내부I/O: USB3.0/2.0 헤더, USB3.1 Type C 헤더, RGB 12V 4핀 헤더, ARGB 5V 3핀 헤더, 펌프전용 헤더, 시스템팬 4핀 4개, TPM 헤더, 디버그LED, 프론트오디오AAFP 헤더",
          "특징: SPS(DrMOS), 전원부 방열판, M.2 히트싱크, UEFI"
        ]
      },
    
      "motherboard5": {
        name: "ASRock B650M Pro X3D 에즈윈",
        category: "motherboard",
        price: "₩193,670",
        image: "./img/motherboard5.png",
        desc: [
          "AMD(소켓AM5), AMD B650, DDR5",
          "VGA 연결: PCIe5.0 x16",
          "M-ATX (24.4x24.4cm)",
          "전원부: 8+2+1페이즈",
          "메모리: 8000MHz (PC5-64000), 4개, 최대 256GB, EXPO",
          "확장슬롯: PCIe5.0/4.0 / PCIex16: 1개 / PCIex4: 1개",
          "저장장치: M.2 3개(PCIe5.0/4.0/NVMe/PCIe 레인공유), SATA3 4개",
          "후면단자: HDMI, DP, USB3.x 10Gbps/5Gbps, USB 2.0, RJ-45, 오디오잭, BIOS플래시백",
          "USB A타입: 7개, USB C타입: 1개",
          "유선랜: Dragon RTL8125BG 2.5Gbps, RJ-45 1개",
          "M.2 Key-E(모듈별매)",
          "오디오: Realtek ALC897, 7.1채널(8ch)",
          "내부I/O: USB3.0/2.0 헤더, USB3.2 Type C 헤더, USB3.0 Type C 헤더, RGB 12V 4핀 헤더, ARGB 5V 3핀 헤더, CPU추가팬(OPT) 헤더, 시스템팬 4핀 3개, TPM 헤더, 프론트오디오AAFP 헤더",
          "특징: DrMOS, 전원부 방열판, M.2 히트싱크, 일체형IO실드, LED라이트, UEFI",
          "23년 11월부로 지원메모리 속도 및 용량 192GB로 확장"
        ]
      }

};
    
const ramProducts = {
  "ram1": {
name: "삼성전자 DDR5-5600 (16GB)",
category: "ram",
price: "₩74,650",
image: "./img/ram1.png",
desc: [
  "데스크탑용",
  "DDR5",
  "5600MHz (PC5-44800)",
  "용량: 16GB (1개)",
  "램타이밍: 표준",
  "전압: 1.10V",
  "온다이ECC: 미지원",
  "히트싱크: 미포함",
  "높이: 표준",
  "모듈제조사: 삼성전자"
]
},

"ram2": {
name: "TeamGroup DDR5-5600 CL46 Elite 서린 (16GB)",
category: "ram",
price: "₩63,450",
image: "./img/ram2.png",
desc: [
  "데스크탑용",
  "DDR5",
  "5600MHz (PC5-44800)",
  "용량: 16GB (1개)",
  "램타이밍: CL46-46-46-90",
  "전압: 1.10V",
  "온다이ECC: 지원",
  "히트싱크: 미포함",
  "높이: 32mm"
]
},

"ram3": {
name: "ESSENCORE KLEVV DDR5-5600 CL46 파인인포 (16GB)",
category: "ram",
price: "₩125,230",
image: "./img/ram3.png",
desc: [
  "데스크탑용",
  "DDR5",
  "5600MHz (PC5-44800)",
  "용량: 16GB (1개)",
  "램타이밍: CL46-46-46-90",
  "전압: 1.10V",
  "온다이ECC: 지원",
  "히트싱크: 미포함",
  "높이: 31.25mm",
  "모듈제조사: SK하이닉스",
  "A다이 언락"
]
},

"ram4": {
name: "마이크론 Crucial DDR4-3200 CL22 대원씨티에스 (16GB)",
category: "ram",
price: "₩38,000",
image: "./img/ram4.png",
desc: [
  "데스크탑용",
  "DDR4",
  "3200MHz (PC4-25600)",
  "용량: 16GB (1개)",
  "램타이밍: CL22",
  "전압: 1.20V",
  "온다이ECC: 미지원",
  "히트싱크: 미포함",
  "높이: 표준"
]
},

"ram5": {
name: "G.SKILL DDR5-6000 CL32 TRIDENT Z5 NEO RGB J 패키지",
category: "ram",
price: "₩363,940",
image: "./img/ram5.png",
desc: [
  "데스크탑용",
  "DDR5",
  "6000MHz (PC5-48000)",
  "용량: 32GB (16GB x2)",
  "램타이밍: CL32-38-38-96",
  "전압: 1.40V",
  "온다이ECC: 지원",
  "히트싱크: 방열판(블랙)",
  "높이: 44mm",
  "LED: RGB",
  "LED 시스템: AURA SYNC, MYSTIC LIGHT, RGB FUSION, POLYCHROME",
  "EXPO 지원"
]
}

};

const ssdProducts = {
  "ssd1": {
name: "삼성전자 980 M.2 NVMe (1TB)",
category: "ssd",
price: "₩119,890",
image: "./img/ssd1.png",
desc: [
  "M.2 (2280)",
  "PCIe3.0x4 (32GT/s)",
  "TLC(토글)",
  "컨트롤러: 삼성 Pablo",
  "순차읽기: 3,100MB/s",
  "순차쓰기: 2,600MB/s",
  "읽기IOPS: 400K",
  "쓰기IOPS: 470K",
  "TRIM, GC, SLC캐싱, S.M.A.R.T, DEVSLP, HMB, AES 암호화, 전용 S/W",
  "MTBF: 150만시간",
  "TBW: 300TB",
  "A/S기간: 5년, 제한보증",
  "방열판 미포함",
  "두께: 2.38mm",
  "무게: 8g"
]
},

"ssd2": {
name: "SK하이닉스 Platinum P41 M.2 NVMe (1TB)",
category: "ssd",
price: "₩147,870",
image: "./img/ssd2.png",
desc: [
  "M.2 (2280)",
  "PCIe4.0x4 (64GT/s)",
  "TLC(토글)",
  "DRAM 탑재: DDR4 1GB",
  "컨트롤러: SK하이닉스 Aries",
  "순차읽기: 7,000MB/s",
  "순차쓰기: 6,500MB/s",
  "읽기IOPS: 1,400K",
  "쓰기IOPS: 1,300K",
  "TRIM, GC, SLC캐싱, S.M.A.R.T, DEVSLP, AES 암호화, 전용 S/W",
  "MTBF: 150만시간",
  "TBW: 750TB",
  "PS5 호환",
  "A/S기간: 5년, 제한보증",
  "방열판 미포함",
  "두께: 2.38mm",
  "무게: 7g"
]
},

"ssd3": {
name: "Western Digital WD BLACK SN850X M.2 NVMe (1TB)",
category: "ssd",
price: "₩129,930",
image: "./img/ssd3.png",
desc: [
  "M.2 (2280)",
  "PCIe4.0x4 (64GT/s)",
  "TLC",
  "DRAM 탑재: DDR4 2GB",
  "컨트롤러: WD",
  "순차읽기: 7,300MB/s",
  "순차쓰기: 6,600MB/s",
  "읽기IOPS: 1,200K",
  "쓰기IOPS: 1,100K",
  "TRIM, SLC캐싱, S.M.A.R.T, 전용 S/W",
  "TBW: 1,200TB",
  "PS5 호환",
  "A/S기간: 5년, 제한보증",
  "방열판 미포함",
  "두께: 2.38mm",
  "무게: 7.5g"
]
},

"ssd4": {
name: "솔리다임 P44 Pro M.2 NVMe 벌크",
category: "ssd",
price: "₩121,600",
image: "./img/ssd4.png",
desc: [
  "M.2 (2280)",
  "PCIe4.0x4 (64GT/s)",
  "TLC(토글)",
  "DRAM 탑재: DDR4 2GB",
  "컨트롤러: SK하이닉스 Aries",
  "순차읽기: 7,000MB/s",
  "순차쓰기: 6,500MB/s",
  "읽기IOPS: 1,400K",
  "쓰기IOPS: 1,300K",
  "TRIM, SLC캐싱, S.M.A.R.T, AES 암호화",
  "MTBF: 160만시간",
  "TBW: 1,200TB",
  "PS5 호환",
  "A/S기간: 3년, 제한보증",
  "방열판 미포함",
  "두께: 2.38mm",
  "무게: 7g"
]
},

"ssd5": {
name: "ESSENCORE KLEVV CRAS C910 M.2 NVMe (1TB)",
category: "ssd",
price: "₩85,090",
image: "./img/ssd5.png",
desc: [
  "M.2 (2280)",
  "PCIe4.0x4 (64GT/s)",
  "TLC",
  "컨트롤러: InnoGrit IG5220",
  "순차읽기: 5,000MB/s",
  "순차쓰기: 4,800MB/s",
  "읽기IOPS: 620K",
  "쓰기IOPS: 615K",
  "TRIM, SLC캐싱, S.M.A.R.T, ECC, HMB, AES 암호화, 전용 S/W",
  "TBW: 700TB",
  "A/S기간: 5년, 제한보증",
  "방열판 포함",
  "두께: 3.4mm",
  "무게: 10g"
]
}

};


const hddProducts = {
  "hdd1": {
name: "Seagate BarraCuda 5400/256M (8TB)",
category: "hdd",
price: "₩199,260",
image: "./img/hdd1.png",
desc: [
  "HDD (PC용)",
  "8.9cm(3.5인치)",
  "8TB",
  "SATA3(6Gb/s)",
  "5,400RPM",
  "메모리 256MB",
  "최대전송속도: 190MB/s",
  "기록방식: SMR(PMR)",
  "두께: 26.11mm",
  "소음(유휴/탐색): 23/25dB",
  "A/S 정보: 2년",
  "다층캐싱(MTC)",
  "무게: 630g"
]
},

"hdd2": {
name: "Western Digital WD Blue 5400/256M (6TB)",
category: "hdd",
price: "₩186,190",
image: "./img/hdd2.png",
desc: [
  "HDD (PC용)",
  "8.9cm(3.5인치)",
  "6TB",
  "SATA3(6Gb/s)",
  "5,400RPM",
  "메모리 256MB",
  "최대전송속도: 180MB/s",
  "기록방식: CMR(PMR)",
  "두께: 26.1mm",
  "소음(유휴/탐색): 23/27dB",
  "A/S 정보: 2년",
  "NoTouch 램프로드 기술"
]
},

"hdd3": {
name: "Seagate BarraCuda 7200/256M (2TB)",
category: "hdd",
price: "₩85,310",
image: "./img/hdd3.png",
desc: [
  "HDD (PC용)",
  "8.9cm(3.5인치)",
  "2TB",
  "SATA3 (6Gb/s)",
  "7,200RPM",
  "메모리 256MB",
  "최대전송속도: 220MB/s",
  "기록방식: SMR(PMR)",
  "두께: 20.2mm",
  "A/S 정보: 2년",
  "다층캐싱(MTC)",
  "무게: 최대 490g"
]
},

"hdd4": {
name: "Western Digital WD Blue 5640/256M (8TB)",
category: "hdd",
price: "₩195,070",
image: "./img/hdd4.png",
desc: [
  "HDD (PC용)",
  "8.9cm(3.5인치)",
  "8TB",
  "SATA3(6Gb/s)",
  "5,640RPM",
  "메모리 256MB",
  "최대전송속도: 215MB/s",
  "기록방식: CMR(PMR)",
  "두께: 26.1mm",
  "소음(유휴/탐색): 24/28dB",
  "A/S 정보: 2년"
]
},

"hdd5": {
name: "Seagate IronWolf 5400/256M (8TB)",
category: "hdd",
price: "₩326,540",
image: "./img/hdd5.png",
desc: [
  "HDD (NAS용)",
  "8.9cm(3.5인치)",
  "8TB",
  "SATA3 (6Gb/s)",
  "5,400RPM",
  "메모리 256MB",
  "최대전송속도: 202MB/s",
  "기록방식: CMR(PMR)",
  "두께: 26.11mm",
  "RV센서",
  "S.M.A.R.T 지원",
  "사용보증: 100만시간",
  "소음(유휴/탐색): 25/26dB",
  "A/S 정보: 3년, 데이터 복구 3년",
  "무게: 630g"
]
}


};


const powerProducts = {
  "power1": {
name: "마이크로닉스 Classic II 풀체인지 700W 80PLUS브론즈 ATX3.1",
category: "power",
price: "₩83,560",
image: "./img/power1.png",
desc: [
  "ATX 파워",
  "정격 700W",
  "80 PLUS 브론즈",
  "케이블연결: 케이블일체형",
  "ETA인증: BRONZE",
  "LAMBDA인증: STANDARD",
  "전압변동: ±0.3%",
  "+12V 싱글레일, +12V 가용률 100%",
  "액티브PFC, PF(역률): 99%",
  "120mm 팬, 깊이: 140mm",
  "무상 7년",
  "커넥터: 메인전원 24핀(20+4), 보조전원 8+4+4핀 1개, PCIe 16핀(12+4) 12V2x6 1개, PCIe 8핀(6+2) 2개, SATA 6개, IDE 4핀 4개",
  "팬리스모드, 자동 팬 조절, 대기전력 1W 미만, 플랫케이블"
]
},

"power2": {
name: "잘만 GigaMax III 850W 80PLUS브론즈 모듈러 ATX3.1",
category: "power",
price: "₩91,220",
image: "./img/power2.png",
desc: [
  "ATX 파워",
  "정격 850W",
  "80 PLUS 브론즈",
  "케이블연결: 세미모듈러",
  "ETA인증: SILVER",
  "LAMBDA인증: STANDARD++",
  "+12V 싱글레일, +12V 가용률 100%",
  "액티브PFC, PF(역률): 99%",
  "120mm 팬, 깊이: 140mm",
  "무상 7년",
  "커넥터: 메인전원 24핀, 보조전원 8+4+4핀 1개, PCIe 16핀(12+4) 12V2x6 1개, PCIe 8핀(6+2) 4개, SATA 6개, IDE 4핀 3개",
  "대기전력 1W 미만, 플랫케이블"
]
},

"power3": {
name: "darkFlash 퍼펙트모스트 850W 80PLUS골드 풀모듈러 ATX3.1 블랙",
category: "power",
price: "₩110,600",
image: "./img/power3.png",
desc: [
  "ATX 파워",
  "정격 850W",
  "80 PLUS 골드",
  "케이블연결: 풀모듈러",
  "+12V 싱글레일, +12V 가용률 100%",
  "액티브PFC, PF(역률): 99%",
  "120mm 팬, 깊이: 140mm",
  "무상 10년",
  "커넥터: 메인전원 24핀(20+4), 보조전원 8핀(4+4) 2개, PCIe 16핀(12+4) 12V2x6 1개, PCIe 8핀(6+2) 3개, SATA 7개, IDE 4핀 5개",
  "팬리스모드, 자동 팬 조절, 대기전력 1W 미만"
]
},

"power4": {
name: "시소닉 NEW FOCUS V4 GX-1000 GOLD 풀모듈러 ATX3.1",
category: "power",
price: "₩244,980",
image: "./img/power4.png",
desc: [
  "ATX 파워",
  "정격 1000W",
  "80 PLUS 골드",
  "케이블연결: 풀모듈러",
  "ETA인증: GOLD",
  "LAMBDA인증: A-",
  "+12V 싱글레일, +12V 가용률 99%",
  "액티브PFC, PF(역률): 99%",
  "135mm 팬, 깊이: 140mm",
  "무상 10년",
  "커넥터: 메인전원 24핀(20+4), 보조전원 8핀(4+4) 2개, PCIe 16핀(12+4) 12V2x6 1개, PCIe 8핀(6+2) 3개, SATA 8개, IDE 4핀 3개",
  "팬리스모드, 자동 팬 조절, 대기전력 1W 미만"
]
},

"power5": {
name: "마이크로닉스 Classic II 850W 80PLUS골드 풀모듈러 ATX3.1",
category: "power",
price: "₩168,960",
image: "./img/power5.png",
desc: [
  "ATX 파워",
  "정격 850W",
  "80 PLUS 골드",
  "케이블연결: 풀모듈러",
  "+12V 싱글레일",
  "액티브PFC, PF(역률): 99%",
  "120mm 팬, 깊이: 140mm",
  "무상 10년",
  "커넥터: 메인전원 24핀(20+4), 보조전원 8+4+4핀 1개, PCIe 16핀(12+4) 12V2x6 1개, PCIe 8핀(6+2) 2개, SATA 8개, IDE 4핀 4개, FDD 1개",
  "팬리스모드, 자동 팬 조절, 대기전력 1W 미만, 플랫케이블"
]
},

};



// 카테고리별 상품 데이터가 이미 정의되어 있다고 가정
// 예: const cpuProducts = { ... }, const vgaProducts = { ... }, ...

// 1. 카테고리 매핑 객체를 window에 등록
window.categoryMap = {
cpu: cpuProducts,
cooler: coolerProducts,
motherboard: motherboardProducts,
ram: ramProducts,
vga: vgaProducts,
ssd: ssdProducts,
hdd: hddProducts,
power: powerProducts
};

// 2. renderProducts 함수 정의
function renderProducts(filterCategory, filters = {}) {
const container = document.getElementById('product-list-container');
if (!container) return;
container.innerHTML = '';

if (!window.categoryMap[filterCategory]) return;

const allProducts = Object.entries(window.categoryMap[filterCategory]);

// 1. 모든 필터 값을 하나의 배열로 추출 (중복 제거)
const allFilterValues = Object.values(filters)
  .flat()
  .map(v => v.toLowerCase());

// 2. 상품 필터링
const filteredProducts = allProducts.filter(([id, product]) => {
  if (allFilterValues.length === 0) return true;

  // 3. 상품 정보 문자열화 (이름 + 설명)
  const productInfo = [
    product.name, 
    ...(Array.isArray(product.desc) ? product.desc : [])
  ].join(' ').toLowerCase();

  // 4. 모든 필터 값이 상품 정보에 포함되는지 확인 (AND 조건)
  return allFilterValues.every(filterValue => 
    productInfo.includes(filterValue)
  );
});

// ★ 콘솔에 필터링된 상품만 표로 출력 (기존 내용 지우고 새로 출력)
console.clear();
console.table(
  filteredProducts.map(([id, product]) => ({
    이름: product.name,
    가격: product.price,
    카테고리: product.category || filterCategory
  }))
);

// 5. 필터링된 상품 렌더링
filteredProducts.forEach(([id, product]) => {
  const descHtml = (Array.isArray(product.desc) ? product.desc : []).join(" / ");
  const html = `
    <div class="product-list-item">
      <div class="product-image">
        <img src="${product.image}" alt="${product.name}">
      </div>
      <div class="product-main-info">
        <div class="product-title">
          <a href="product.html?id=${id}" class="product-link">
            ${product.name}
          </a>
        </div>
        <div class="product-desc">${descHtml}</div>
      </div>
      <div class="product-price-box">
        <div class="product-price">${product.price}</div>
      </div>
    </div>
  `;
  container.insertAdjacentHTML('beforeend', html);
});
}

// 3. 전역 함수 등록 (store.js 등에서 호출 가능하게)
window.renderProducts = renderProducts;



